admin_search.area:
    resource: "@adminBundle/Controller/search_areaController.php"
    type:     annotation

admin_frontend.contact.us:
    resource: "@adminBundle/Controller/frontend_contact_usController.php"
    type:     annotation

admin_frontend.services:
    resource: "@adminBundle/Controller/frontend_servicesController.php"
    type:     annotation

admin_frontend.about:
    resource: "@adminBundle/Controller/frontend_aboutController.php"
    type:     annotation

admin_categorie.user:
    resource: "@adminBundle/Controller/categorie_userController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

customer:
    resource: "@CustomerBundle/Controller/"
    type:     annotation

admin:
    resource: "@adminBundle/Controller/"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_user:
    resource: "@adminBundle/Controller/UserController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_register:
    path:      /adminstration/register
    defaults:  { _controller: adminBundle:Registration:register }


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /admin

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect


hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    path: /connect/check-facebook

google_login:
    path: /connect/check-google