<?php

namespace adminBundle\Repository;

/**
 * categorie_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorie_userRepository extends \Doctrine\ORM\EntityRepository
{
}
