<?php

namespace adminBundle\Repository;

/**
 * category_itemesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class category_itemesRepository extends \Doctrine\ORM\EntityRepository
{
}
