<?php

namespace adminBundle\Repository;

/**
 * frontend_contact_usRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class frontend_contact_usRepository extends \Doctrine\ORM\EntityRepository
{
}
