<?php

namespace adminBundle\Repository;

/**
 * frontend_aboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class frontend_aboutRepository extends \Doctrine\ORM\EntityRepository
{
}
