<?php

namespace adminBundle\Repository;

/**
 * information_customerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class information_customerRepository extends \Doctrine\ORM\EntityRepository
{
}
