<?php

namespace adminBundle\Repository;

/**
 * search_areaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class search_areaRepository extends \Doctrine\ORM\EntityRepository
{
}
